name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23.6'
          cache: 'pnpm'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.4.27'
      - run: pnpm install
      - run: pnpm nx run-many -t test,build,package

      - name: Upload APKGs
        uses: actions/upload-artifact@v4.4.3
        with:
          name: APKGs
          path: release/

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.4.27'
      - run: pnpm install
      - run: pnpm nx run-many -t lint,typecheck,lint:py
