name: Playground

on:
  push:
    branches: [main]

jobs:
  build:
    if: |
      startsWith(github.event.head_commit.message , 'chore: release playground')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23.6'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
      - run: pnpm run build

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.4.27'
      - name: Package Test
        run: pnpm run package
      - name: Build playground
        run: pnpm run pg-build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'ikkz-template'
          directory: 'playground/dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
