name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - run: pnpm install
      - run: node cli.js

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.4.27'
      - name: Release
        run: uv run --frozen release.py
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: 'release/*.apkg'
          artifactErrorsFailBuild: true
